import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from '@/components/Topbar'
import Footer from '@/components/Footer'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "achraf-blog",
  description: "Generated by create next app",
  author: "Your Name",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <div className="flex flex-col min-h-screen">
          <Topbar />
          <main className="flex-grow pt-10">
            <ToastContainer />
            {children}
          </main>
          <Footer />
        </div>
        </body>
    </html>
  );
}
